# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./client  # Change to your React app path
#     ports:
#       - "3000:80"

#   backend:
#     build:
#       context: ./server  # Change to your Express app path
#     ports:
#       - "3008:3007"
#     environment:
#       - PGUSER=postgres
#       - PGHOST=db
#       - PGDATABASE=spotify_project
#       - PGPASSWORD=Monkeybusiness
#       - PGPORT=5432
#     depends_on:
#       - db

#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: Monkeybusiness
#       POSTGRES_DB: spotify_project
#     ports:
#       - "5432:5432"
